# Use official Python base image
FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y build-essential cmake git libgl1-mesa-glx libglib2.0-0 && \
    apt-get clean

# Set working directory
WORKDIR /app

# Clone DeslantImg
# RUN git clone https://github.com/githubharald/DeslantImg.git
WORKDIR /app/DeslantImg

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy Gradio app code
COPY deslant_app.py /app/deslant_app.py

# Set working directory to root app
WORKDIR /app

# Expose Gradio default port
EXPOSE 7860

# Run the app
CMD ["python", "deslant_app.py"]
